build:
	sam build

deploy:
	sam deploy

deploy-guided:
	sam deploy --guided

destroy:
	aws --region us-east-1 --profile investing_scrapping cloudformation delete-stack --stack-name investing-scrapping-v2