version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "investing-scrapping-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wydwg391su74"
s3_prefix = "investing-scrapping-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

